### ISSUE TITLE
add header Fields to fix "Access to fetch"

### ISSUE THREAD

**Issue by lopins** [aiql-community/chat-ui-lite#2]
![image](https://github.com/user-attachments/assets/254182e4-3635-4f35-89d2-cb0a5fb9dfb3)

Access to fetch at 'https://integrate.api.nvidia.com/v1/chat/completions' from origin

**Comment by aiqlcom** [comment]
This isn't an issue, but a common cross-origin problem. Nvidia-NIM is a private backend, so cross-origin access is not allowed without a wildcard configuration. You need to access it through another backend and enable CORS for this backend service.

Here is a ready-to-use backend that I deployed for Nvidia-NIM: 

![20241006103613](https://github.com/user-attachments/assets/4c9939bd-60d2-4fd7-a724-be65fa283d1a)
