### ISSUE TITLE
RAG Settings interface without i18n

### ISSUE THREAD

**Issue by lopins** [aiql-community/chat-ui-lite#3]

**Comment by aiqlcom** [comment]
Thank you for your reminder. You're referring to the agent/prompt configuration interface hidden in the toolkit sidebar. 

We are still considering how to better implement this interface, so currently, we only provide basic prompt functionality. 

Given the wide variety of agent/RAG-related systems on the market, and the lack of standardized API interfaces like those of OpenAI, we don't yet have a clear plan for how to further improve this experimental interface.
