### ISSUE TITLE
[Question] How does it work without an api key or running locally?

### ISSUE THREAD

**Issue by RiyanDutta** [aiql-community/chat-ui-lite#4]
Is there some sort of rate limit?

**Comment by aiqlcom** [comment]
The API currently used in the demo is a basic backend with daily usage limits and query rate restrictions (exceeding these limits will result in a model response with error code 429). 

For production use, you can integrate any backend in the interface config. 
I have included configuration examples for commercial backends in the example/config. 

Alternatively, you can deploy your own backend using vLLM and TGI. In my daily workflow, I use this UI as the frontend with vLLM serving as the backend.
